-- Persist batch invitation verification reports so Master Administrators can
-- reopen and refresh them after a browser reload or on another device.

create table if not exists public.batch_invitation_reports (
  batch_id uuid primary key,
  created_by uuid not null references auth.users(id) on delete restrict,
  file_name text not null default 'Batch upload',
  total_count integer not null default 0 check (total_count between 0 and 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.batch_invitation_report_items (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.batch_invitation_reports(batch_id) on delete cascade,
  row_number integer,
  first_name text,
  last_name text,
  email text not null,
  status text not null,
  message text,
  event text,
  resend_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (batch_id, email)
);

create index if not exists batch_invitation_reports_created_at_idx
  on public.batch_invitation_reports(created_at desc);

create index if not exists batch_invitation_report_items_batch_idx
  on public.batch_invitation_report_items(batch_id, row_number);

alter table public.batch_invitation_reports enable row level security;
alter table public.batch_invitation_report_items enable row level security;

revoke all on public.batch_invitation_reports from public, anon, authenticated;
revoke all on public.batch_invitation_report_items from public, anon, authenticated;

comment on table public.batch_invitation_reports is
  'Server-managed history of administrator batch invitation verification reports.';
comment on table public.batch_invitation_report_items is
  'Per-recipient delivery status and Resend identifier for persistent batch verification reports.';
