'use client';

import {useEffect,useMemo,useState} from 'react';

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const readSession=()=>{try{return JSON.parse(localStorage.getItem('compassu_session')||'null')}catch{return null}};
const labelize=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const dateLabel=v=>{if(!v)return '';const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})};
const periodLabel=p=>`${dateLabel(p.period_start)} – ${dateLabel(p.period_end)}`;

export default function AdminTrendAnalyticsPanel(){
 const[session,setSession]=useState(null),[institutions,setInstitutions]=useState([]),[institution,setInstitution]=useState(''),[months,setMonths]=useState(12),[count,setCount]=useState(4),[through,setThrough]=useState(new Date().toISOString().slice(0,10)),[trends,setTrends]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const headers=s=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',Authorization:`Bearer ${s?.access_token||''}`});
 async function loadInstitutions(s){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/account_institutions?select=institution&institution=not.is.null`,{headers:headers(s)});const b=await r.json();if(!r.ok)throw new Error();setInstitutions([...new Set((b||[]).map(x=>String(x.institution||'').trim()).filter(Boolean))].sort())}catch{}}
 async function loadTrends(s=session){if(!s?.access_token)return;setBusy(true);setError('');try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/get_institutional_trends`,{method:'POST',headers:headers(s),body:JSON.stringify({p_institution:institution||null,p_period_months:Number(months),p_period_count:Number(count),p_end_date:through||null})});const b=await r.json();if(!r.ok)throw new Error(b?.message||b?.error||b?.hint||'Unable to load institutional trends');setTrends(b)}catch(e){setTrends(null);setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{let token='';const sync=()=>{const s=readSession(),t=s?.access_token||'';if(t===token)return;token=t;if(!t){setSession(null);setTrends(null);return}setSession(s);loadInstitutions(s)};sync();const timer=setInterval(sync,500);return()=>clearInterval(timer)},[]);
 const periods=trends?.periods||[];const completionMax=useMemo(()=>Math.max(1,...periods.map(p=>Number(p.participation?.completion_rate||0))),[periods]);
 if(!session)return null;
 return <section className="trendPanel adminPanel"><div className="trendHead"><div><div className="adminKicker">STAGE 2C</div><h2>Institutional Trends</h2><p>Review longitudinal changes across consecutive reporting periods. Trend results use aggregate data and the same small-cell privacy safeguards as Institutional Analytics.</p></div><div className="trendControls"><select value={institution} onChange={e=>setInstitution(e.target.value)}><option value="">All Institutions</option>{institutions.map(v=><option key={v}>{v}</option>)}</select><label><span>Period length</span><select value={months} onChange={e=>setMonths(Number(e.target.value))}><option value={3}>Quarterly (3 months)</option><option value={6}>Semiannual (6 months)</option><option value={12}>Annual (12 months)</option></select></label><label><span>Periods</span><select value={count} onChange={e=>setCount(Number(e.target.value))}><option value={2}>2 periods</option><option value={3}>3 periods</option><option value={4}>4 periods</option><option value={5}>5 periods</option><option value={6}>6 periods</option></select></label><label><span>Through</span><input type="date" value={through} onChange={e=>setThrough(e.target.value)}/></label><button className="btn primary" disabled={busy} onClick={()=>loadTrends()}>{busy?'Loading…':'Load Trends'}</button></div></div>{error&&<div className="error adminNotice">{error}</div>}{busy&&!trends&&<div className="analyticsLoading">Loading institutional trends…</div>}{trends&&<TrendResults trends={trends} periods={periods} completionMax={completionMax}/>}</section>
}

function TrendResults({trends,periods,completionMax}){
 const threshold=trends?.privacy?.small_cell_threshold??5;
 const dimensions=[...new Set(periods.flatMap(p=>(p.dimensions||[]).filter(x=>!x.suppressed).map(x=>x.dimension)))];
 const hasMeaningfulHistory=periods.filter(p=>(p.participation?.completed_students||0)>=threshold).length>=2;
 return <div className="trendResults">{!hasMeaningfulHistory&&<div className="trendNotice"><b>Limited historical data.</b> CompassU can display the available periods, but at least two periods with {threshold} or more completed students are recommended before interpreting longitudinal patterns.</div>}<div className="trendCard"><h3>Completion Trend</h3><p className="analyticsSub">Completion rate and completed-student volume by reporting period.</p><div className="trendBars">{periods.map(p=>{const rate=Number(p.participation?.completion_rate||0);return <div className="trendBarItem" key={p.period_start}><div className="trendBarValue">{rate}%</div><div className="trendBarTrack"><i style={{height:`${Math.max(3,Math.round(rate/completionMax*100))}%`}}/></div><b>{p.participation?.completed_students??0}</b><span>{periodLabel(p)}</span></div>})}</div></div><div className="trendCard"><h3>Six-Dimension Trend</h3><p className="analyticsSub">Average normalized profile scores by period. Privacy-suppressed cells display as unavailable.</p><div className="comparisonTableWrap"><table className="comparisonTable compact"><thead><tr><th>Dimension</th>{periods.map(p=><th key={p.period_start}>{periodLabel(p)}</th>)}</tr></thead><tbody>{dimensions.map(d=><tr key={d}><td>{labelize(d)}</td>{periods.map(p=>{const x=(p.dimensions||[]).find(v=>v.dimension===d);return <td key={p.period_start}>{x&&!x.suppressed&&x.average_score!=null?`${x.average_score}%`:'—'}</td>})}</tr>)}</tbody></table></div>{!dimensions.length&&<div className="adminEmpty">No dimension cells currently reach the privacy threshold.</div>}</div><div className="trendGrid"><TrendRankCard title="Leading Career Clusters" periods={periods} field="career_clusters" name="cluster"/><TrendRankCard title="Recurring Major Alignments" periods={periods} field="top_majors" name="major_name"/><TrendRankCard title="Recurring Career Alignments" periods={periods} field="top_careers" name="occupation_name"/></div><div className="analyticsPrivacy">Trend safeguard: categories representing fewer than {threshold} students remain suppressed. Periods are descriptive snapshots of CompassU assessment activity and should not be interpreted as causal changes in institutional performance.</div></div>
}

function TrendRankCard({title,periods,field,name}){return <div className="trendCard"><h3>{title}</h3><div className="trendRankList">{periods.map(p=>{const items=(p[field]||[]).filter(x=>!x.suppressed).slice(0,3);return <div key={p.period_start}><b>{periodLabel(p)}</b>{items.length?items.map((x,i)=><span key={`${x[name]}-${i}`}>{i+1}. {labelize(x[name])} · {x.student_count}</span>):<span>No reportable cells</span>}</div>})}</div></div>}
