'use client';

import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim());
const cleanHeader=v=>String(v||'').toLowerCase().replace(/[^a-z]/g,'');
const readSession=()=>{try{return JSON.parse(localStorage.getItem('compassu_session')||'null')}catch{return null}};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const finalStatuses=new Set(['Delivered','Bounced','Complained','Failed','Suppressed']);

export default function BatchInvite500(){
 const[target,setTarget]=useState(null),[rows,setRows]=useState([]),[fileName,setFileName]=useState(''),[results,setResults]=useState([]),[sending,setSending]=useState(false),[checking,setChecking]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{const find=()=>{const el=document.querySelector('.adminBatch');if(el){el.classList.add('batch500Enhanced');setTarget(el);return true}return false};if(find())return;const obs=new MutationObserver(()=>{if(find())obs.disconnect()});obs.observe(document.body,{childList:true,subtree:true});return()=>obs.disconnect()},[]);
 const callFunction=async(name,payload)=>{const s=readSession();if(!s?.access_token)throw new Error('Administrator login required.');const r=await fetch(`${SUPABASE_URL}/functions/v1/${name}`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`},body:JSON.stringify(payload)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Administrator request failed');return b};
 const callAdmin=payload=>callFunction('admin-console',payload);
 const callBatch=async payload=>{let last;for(let attempt=0;attempt<3;attempt++){try{return await callAdmin(payload)}catch(e){last=e;if(attempt<2)await wait(750*(attempt+1))}}throw last};
 const ready=useMemo(()=>rows.filter(r=>r.status==='Ready'),[rows]);
 const counts=useMemo(()=>({registered:rows.filter(r=>r.status==='Already registered').length,duplicate:rows.filter(r=>r.status==='Duplicate in file').length,invalid:rows.filter(r=>r.status==='Invalid email').length}),[rows]);
 const parseFile=async e=>{const file=e.target.files?.[0];if(!file)return;setError('');setNotice('');setResults([]);setProgress(0);try{const XLSX=await import('xlsx');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const raw=XLSX.utils.sheet_to_json(ws,{defval:''});if(!raw.length)throw new Error('The spreadsheet does not contain any invitation rows.');if(raw.length>500)throw new Error(`This file contains ${raw.length} rows. CompassU accepts a maximum of 500 participants per batch.`);const overview=await callAdmin({action:'overview'});const existing=new Set((overview?.users||[]).map(u=>String(u.email||'').trim().toLowerCase()));const seen=new Set();const parsed=raw.map((r,i)=>{const m={};Object.entries(r).forEach(([k,v])=>m[cleanHeader(k)]=v);const first_name=String(m.firstname||m.first||'').trim(),last_name=String(m.lastname||m.last||'').trim(),email=String(m.email||m.emailaddress||'').trim().toLowerCase();let status='Ready';if(!validEmail(email))status='Invalid email';else if(seen.has(email))status='Duplicate in file';else if(existing.has(email))status='Already registered';if(email)seen.add(email);return{row:i+2,first_name,last_name,email,status}});setRows(parsed);setFileName(file.name)}catch(err){setRows([]);setFileName('');setError(err.message||'Unable to read the spreadsheet.')}finally{e.target.value=''}};
 const refreshDelivery=async(source=results)=>{const candidates=source.filter(r=>['Submitted','Pending delivery','Delayed','Sent'].includes(r.status));if(!candidates.length)return source;setChecking(true);setError('');try{const b=await callFunction('admin-email-status',{emails:candidates.map(r=>r.email)});const map=new Map((b.results||[]).map(r=>[String(r.email||'').toLowerCase(),r]));const updated=source.map(r=>{const s=map.get(String(r.email||'').toLowerCase());return s?{...r,status:s.status,message:s.message,event:s.event||''}:r});setResults(updated);const delivered=updated.filter(r=>r.status==='Delivered').length,bounced=updated.filter(r=>r.status==='Bounced').length,pending=updated.filter(r=>['Submitted','Pending delivery','Delayed'].includes(r.status)).length,failed=updated.filter(r=>['Failed','Suppressed','Complained'].includes(r.status)).length;setNotice(`Delivery check: ${delivered} delivered, ${bounced} bounced, ${failed} failed/suppressed${pending?`, ${pending} still pending`:''}.`);return updated}catch(err){setError(err.message||'Unable to refresh delivery status.');return source}finally{setChecking(false)}};
 const send=async()=>{if(!ready.length)return;if(!window.confirm(`Send ${ready.length} CompassU invitations? The system will process them in secure batches of up to 100.`))return;setSending(true);setError('');setNotice('');setResults([]);setProgress(0);const all=[],batchId=crypto.randomUUID();try{for(let i=0;i<ready.length;i+=100){const chunk=ready.slice(i,i+100),chunkIndex=Math.floor(i/100);const payload={action:'batch_invite',batch_id:batchId,chunk_index:chunkIndex,people:chunk.map(({first_name,last_name,email,row})=>({first_name,last_name,email,row}))};const b=await callBatch(payload);const returned=Array.isArray(b.results)?b.results:[];for(const r of returned){const original=chunk.find(x=>x.email===r.email);all.push({...original,...r,status:r.status==='Sent'?'Submitted':r.status,message:r.status==='Sent'?'Accepted by Resend; final delivery not yet verified.':r.message})}setResults([...all]);setProgress(Math.min(ready.length,i+chunk.length))}const submitted=all.filter(r=>r.status==='Submitted').length,failed=all.filter(r=>r.status==='Failed').length,skipped=all.length-submitted-failed;setNotice(`Batch submitted: ${submitted} accepted by Resend, ${failed} failed${skipped?`, ${skipped} skipped`:''}. Checking delivery status…`);await wait(3500);await refreshDelivery(all)}catch(err){setError(`${err.message||'Batch sending stopped.'} ${all.length?'Completed results are available below.':''}`)}finally{setSending(false)}};
 const download=()=>{const source=results.length?results:rows;if(!source.length)return;const out=[['Row','First Name','Last Name','Email','Status','Message'],...source.map(r=>[r.row,r.first_name,r.last_name,r.email,r.status,r.message||''])];const csv=out.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='CompassU-Batch-Invitation-Results.csv';a.click();URL.revokeObjectURL(url)};
 if(!target)return null;
 const canRefresh=results.some(r=>['Submitted','Pending delivery','Delayed','Sent'].includes(r.status));
 return createPortal(<div className="batch500Root"><h3>Batch Invitations — Up to 500</h3><p>Upload an Excel or CSV file with <b>First Name</b>, <b>Last Name</b>, and <b>Email</b> columns. CompassU validates the file first and nothing is sent until you confirm.</p><label className="batchUpload">Choose Excel / CSV<input type="file" accept=".xlsx,.xls,.csv" onChange={parseFile}/></label>{fileName&&<div className="batchFile">{fileName}</div>}{error&&<div className="batch500Error">{error}</div>}{notice&&<div className="batch500Success">{notice}</div>}{rows.length>0&&<><div className="batchSummary"><b>{rows.length} rows</b><span>{ready.length} ready</span><span>{counts.registered} registered</span><span>{counts.duplicate} duplicates</span><span>{counts.invalid} invalid</span></div><div className="batchPreview">{rows.slice(0,8).map(r=><div className="batchRow" key={r.row}><span>{r.first_name} {r.last_name}<small>{r.email||'No email'}</small></span><b className={r.status==='Ready'?'ok':'warn'}>{r.status}</b></div>)}{rows.length>8&&<div className="batchMore">+ {rows.length-8} more rows</div>}</div>{sending&&<div className="batch500Progress"><div style={{width:`${ready.length?Math.round(progress/ready.length*100):0}%`}}/><span>{progress} of {ready.length} processed</span></div>}<button className="btn primary wide" disabled={sending||checking||!ready.length} onClick={send}>{sending?`Processing ${progress}/${ready.length}…`:`Send ${ready.length} Invitations`}</button>{results.length>0&&<button className="btn ghost wide" disabled={checking||!canRefresh} onClick={()=>refreshDelivery()}>{checking?'Checking Resend…':canRefresh?'Refresh Delivery Status':'Delivery Status Final'}</button>}<button className="btn ghost wide" onClick={download}>{results.length?'Download Results':'Download Validation Report'}</button><div className="batch500Note">“Submitted” means Resend accepted the message for delivery. “Delivered” is only shown after Resend confirms acceptance by the recipient mail server. Bounces, suppressions, and delivery failures are reported separately.</div></>}</div>,target);
}
