import test from 'node:test';
import assert from 'node:assert/strict';
import {validateReceipt,receiptFileName,RECEIPT_MAX_BYTES} from '../lib/receiptValidation.mjs';
import {attachReceipt,downloadReceipt} from '../lib/financeReceipts.js';
const id='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222';
const file=(buffer,type,name='receipt')=>({name,type,size:buffer.length,arrayBuffer:async()=>buffer});
test('accepts supported receipt content and derives safe filenames',async()=>{const cases=[[Buffer.from('%PDF-1.7\n'),'application/pdf','pdf'],[Buffer.from([255,216,255,0]),'image/jpeg','jpg'],[Buffer.from([137,80,78,71,13,10,26,10]),'image/png','png'],[Buffer.from('RIFF0000WEBP'),'image/webp','webp']];for(const [b,m,e]of cases){const r=await validateReceipt(file(b,m,'../receipt.html'));assert.equal(r.mime,m);assert.ok(r.name.endsWith('.'+e));assert.ok(!r.name.includes('/'));}assert.ok(!receiptFileName('"\r\nX-Test: unsafe','pdf').includes('\n'));});
test('rejects empty, oversize, HTML, and mislabeled receipts',async()=>{await assert.rejects(validateReceipt({size:0,arrayBuffer:async()=>Buffer.alloc(0)}));await assert.rejects(validateReceipt({size:RECEIPT_MAX_BYTES+1,arrayBuffer:async()=>{throw Error('must not read oversize')}}),/3 MB/);await assert.rejects(validateReceipt(file(Buffer.from('<html>evil</html>'),'application/pdf')),/Use a PDF/);await assert.rejects(validateReceipt(file(Buffer.from('%PDF-1.7'),'image/png')),/do not match/);});
function secret(t){const old=process.env.SUPABASE_SERVICE_ROLE_KEY;process.env.SUPABASE_SERVICE_ROLE_KEY='sb_secret_test_only';t.after(()=>{if(old===undefined)delete process.env.SUPABASE_SERVICE_ROLE_KEY;else process.env.SUPABASE_SERVICE_ROLE_KEY=old;});}
test('uploads a private file and registers metadata after storage accepts it',async t=>{secret(t);const calls=[];t.mock.method(globalThis,'fetch',async(url,opts)=>{calls.push(String(url));if(String(url).includes('finance_expenses?'))return Response.json([{id}]);if(String(url).includes('finance_expense_receipts?'))return Response.json([]);if(String(url).includes('/storage/v1/object/')){assert.equal(opts.headers.get('x-upsert'),'false');return Response.json({Key:'finance-receipts/test'});}if(String(url).includes('rpc/finance_register_receipt')){const b=JSON.parse(opts.body);assert.equal(b.p_expense,id);assert.ok(b.p_path.startsWith(id+'/'));assert.equal(b.p_actor,actor);return Response.json({expense_id:id,file_name:'receipt.pdf'});}throw Error('Unexpected request '+url);});const r=await attachReceipt(id,await validateReceipt(file(Buffer.from('%PDF-1.7'),'application/pdf')),actor);assert.equal(r.expense_id,id);assert.equal(calls.length,4);});
test('duplicate receipts are rejected before uploading',async t=>{t.mock.method(globalThis,'fetch',async url=>Response.json(String(url).includes('finance_expenses?')?[{id}]:[{id:'existing'}]));secret(t);await assert.rejects(attachReceipt(id,{extension:'pdf'},actor),e=>e.status===409);});
test('failed metadata registration removes the unattached file',async t=>{secret(t);let deleted=false;t.mock.method(globalThis,'fetch',async(url,opts)=>{if(String(url).includes('finance_expenses?'))return Response.json([{id}]);if(String(url).includes('finance_expense_receipts?'))return Response.json([]);if(String(url).includes('rpc/'))return Response.json({message:'metadata unavailable'},{status:500});if(opts.method==='DELETE'){deleted=true;return Response.json([]);}return Response.json({Key:'test'});});await assert.rejects(attachReceipt(id,await validateReceipt(file(Buffer.from('%PDF-1.7'),'application/pdf')),actor));assert.equal(deleted,true);});
test('download rejects paths belonging to another bill',async t=>{secret(t);t.mock.method(globalThis,'fetch',async()=>Response.json([{object_path:'another-bill/receipt.pdf'}]));await assert.rejects(downloadReceipt(id),/Invalid receipt record/);});
