export const metadata = { title: 'Privacy Notice | CompassU' };

const sectionStyle={marginBottom:28};
const h2Style={fontSize:22,margin:'0 0 10px',color:'#0f1d40'};
const pStyle={lineHeight:1.7,color:'#374151'};

export default function PrivacyPage(){
 return <main style={{maxWidth:900,margin:'0 auto',padding:'48px 24px 96px'}}>
  <a href="/" style={{fontWeight:800,color:'#2f6df6',textDecoration:'none'}}>← Back to CompassU</a>
  <h1 style={{fontSize:42,margin:'24px 0 8px',color:'#0f1d40'}}>CompassU Privacy Notice</h1>
  <p style={{...pStyle,color:'#6b7280'}}>Effective September 11, 2026 · Production legal draft for counsel review</p>
  <section style={sectionStyle}><h2 style={h2Style}>1. Scope</h2><p style={pStyle}>This notice explains how CompassU collects, uses, discloses, retains, and protects information when students, educational institutions, administrators, and other authorized users use CompassU.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>2. Information we collect</h2><p style={pStyle}>Depending on use, CompassU may process account and profile information such as name, email address, institution affiliation, graduation year, and state; assessment responses and attempts; derived major, career, and educational recommendations; saved preferences; institutional membership and reporting configuration; and technical, security, audit, and email-delivery information.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>3. How we use information</h2><p style={pStyle}>CompassU uses information to provide and personalize the service, score assessments, generate educational recommendations and reports, support institution-authorized analytics, communicate with users, secure and administer accounts, troubleshoot the service, prevent misuse, and comply with applicable law and contractual obligations.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>4. Student data commitments</h2><p style={pStyle}><strong>CompassU does not sell student personal information, serve targeted advertising based on student data, or use institution-provided student information to build unrelated commercial profiles.</strong> Student information supplied through an educational institution is used only to provide, secure, support, improve, and administer the CompassU educational service as permitted by the institution and applicable law.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>5. Educational institutions and FERPA</h2><p style={pStyle}>When CompassU processes education records on behalf of a participating institution, CompassU acts as a service provider for the authorized educational purpose established by the institution and applicable agreement. Institutions retain the rights applicable to education records under their control. Technical execution of identifiable access, export, modification, and deletion requests is performed exclusively by authorized CompassU Master Administrators after request authentication and authorization.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>6. Minors and COPPA</h2><p style={pStyle}>CompassU is designed primarily for high-school juniors and seniors and college students. CompassU does not intentionally invite independent account creation by children under 13. Any institution-sponsored use involving children under 13 must be specifically authorized and configured in accordance with applicable child-privacy requirements and the CompassU Minors/COPPA Policy.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>7. Institutional reporting</h2><p style={pStyle}>Institutional analytics are designed to use aggregate information by default. CompassU applies institution scoping and may suppress small data cells to reduce re-identification risk. Identifiable operational information is provided only when authorized and necessary for administration or support.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>8. Service providers</h2><p style={pStyle}>CompassU uses service providers to operate its application infrastructure, database and authentication services, hosting, and transactional email. These providers may process information only for services they provide to CompassU and are subject to applicable contractual and security obligations. CompassU maintains a current subprocessor disclosure for institutional customers.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>9. Retention and deletion</h2><p style={pStyle}>CompassU retains information only for periods needed to provide and administer the service, satisfy institution-authorized educational purposes, maintain security and audit records, resolve disputes, and meet legal obligations. Authorized institutions and users may submit access or deletion requests where applicable. CompassU Master Administrators authenticate and execute approved technical requests.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>10. Security</h2><p style={pStyle}>CompassU uses administrative, technical, and organizational safeguards appropriate to the nature of the information processed. No service can guarantee absolute security. Suspected security incidents are handled under the CompassU incident-response and breach-notification process.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>11. Choices and requests</h2><p style={pStyle}>Questions or authorized requests concerning student records should ordinarily be submitted through the participating institution when the institution supplied or controls the information. CompassU may require verification before acting on any request.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>12. Changes</h2><p style={pStyle}>CompassU may update this notice as the service, law, or data practices change. Material revisions will be identified by a new effective date and, when appropriate, additional notice.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>13. Contact</h2><p style={pStyle}>Privacy and data-governance inquiries may be submitted through the official CompassU support or institutional contact channel designated for the applicable deployment.</p></section>
 </main>
}
