export const metadata = { title: 'Terms of Service | CompassU' };

const sectionStyle={marginBottom:28};
const h2Style={fontSize:22,margin:'0 0 10px',color:'#0f1d40'};
const pStyle={lineHeight:1.7,color:'#374151'};

export default function TermsPage(){
 return <main style={{maxWidth:900,margin:'0 auto',padding:'48px 24px 96px'}}>
  <a href="/" style={{fontWeight:800,color:'#2f6df6',textDecoration:'none'}}>← Back to CompassU</a>
  <h1 style={{fontSize:42,margin:'24px 0 8px',color:'#0f1d40'}}>CompassU Terms of Service</h1>
  <p style={{...pStyle,color:'#6b7280'}}>Effective September 11, 2026 · Production legal draft for counsel review</p>
  <section style={sectionStyle}><h2 style={h2Style}>1. Agreement</h2><p style={pStyle}>By creating an account, accessing, or using CompassU, you agree to these Terms and the CompassU Privacy Notice. If you use CompassU through an educational institution, additional institutional agreements may also apply.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>2. Educational purpose</h2><p style={pStyle}>CompassU is an educational decision-support service designed to help users explore majors, careers, occupations, and colleges. Its recommendations are informational and are not guarantees of admission, employment, earnings, academic success, or career outcomes.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>3. Accounts</h2><p style={pStyle}>Users must provide accurate information, protect account credentials, and use only accounts they are authorized to access. Users may not share credentials, impersonate another person, circumvent security controls, scrape restricted data, or interfere with service operation.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>4. Institution-sponsored use</h2><p style={pStyle}>When an institution sponsors access, CompassU may process student information for the educational purposes authorized by that institution. Technical access, export, modification, retention, and deletion operations involving identifiable records are performed exclusively by authorized CompassU Master Administrators following authenticated and authorized requests.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>5. Student data restrictions</h2><p style={pStyle}>CompassU does not sell student personal information, use student data for targeted advertising, or use institution-provided student information for unrelated commercial profiling. Users and institutions may not use CompassU to unlawfully collect, disclose, or exploit another person's information.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>6. Intellectual property</h2><p style={pStyle}>CompassU and its original software, assessment design, interfaces, reports, branding, and related materials are protected by applicable intellectual-property laws. Users receive a limited, revocable, non-transferable right to use the service for authorized educational purposes.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>7. Third-party and public data</h2><p style={pStyle}>CompassU may display information derived from public or licensed sources, including education and labor-market data. Such information can change and may contain delays or inaccuracies. Third-party links are provided for convenience and are governed by the third party's terms.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>8. Availability and changes</h2><p style={pStyle}>CompassU may update, maintain, suspend, or modify features as needed for security, reliability, compliance, or product improvement. CompassU does not guarantee uninterrupted availability.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>9. Suspension and termination</h2><p style={pStyle}>CompassU may suspend or terminate access for security reasons, unlawful use, material violations of these Terms, nonpayment under an applicable institutional agreement, or conduct that threatens users or service integrity.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>10. Disclaimer</h2><p style={pStyle}>To the maximum extent permitted by law, CompassU is provided on an “as available” basis. Educational recommendations are decision-support information and should be considered alongside counseling, academic requirements, admissions information, financial considerations, and individual circumstances.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>11. Limitation and institutional agreements</h2><p style={pStyle}>Any warranties, indemnities, liability allocations, governing law, payment terms, service commitments, or negotiated obligations for an institutional deployment are governed by the applicable signed institutional agreement and, where applicable, its Data Processing Addendum.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>12. Privacy</h2><p style={pStyle}>CompassU's handling of personal information is described in the <a href="/privacy">Privacy Notice</a>. Institution-sponsored student information may also be governed by FERPA-related contractual terms or other applicable education-privacy requirements.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>13. Changes to these Terms</h2><p style={pStyle}>CompassU may revise these Terms. Material revisions will be identified by an updated effective date and, when appropriate, additional notice or renewed acceptance.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>14. Contact</h2><p style={pStyle}>Questions about these Terms may be submitted through the official CompassU support or institutional contact channel designated for the applicable deployment.</p></section>
 </main>
}
