import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]||c));
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
const auth=req.headers.get('Authorization');if(!auth)return json({error:'Missing authorization'},401);
const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,resend=Deno.env.get('RESEND_API_KEY')!,from=Deno.env.get('COMPASSU_FROM_EMAIL')||'CompassU <results@getcompassu.com>',app=(Deno.env.get('COMPASSU_APP_URL')||'https://getcompassu.com').replace(/\/$/,'');
const sh={apikey:service,Authorization:`Bearer ${service}`,'Content-Type':'application/json'};
const ur=await fetch(`${url}/auth/v1/user`,{headers:{apikey:anon,Authorization:auth}});if(!ur.ok)return json({error:'Invalid user session'},401);const me=await ur.json();
const ar=await fetch(`${url}/rest/v1/admin_users?user_id=eq.${me.id}&select=user_id,role&limit=1`,{headers:sh});const admins=await ar.json();if(!admins?.length)return json({error:'Administrator access is not enabled for this account.'},403);
const body=await req.json().catch(()=>({})),action=body.action||'overview';
const allUsers=async()=>{let a:any[]=[],p=1;for(;p<=20;p++){const r=await fetch(`${url}/auth/v1/admin/users?page=${p}&per_page=200`,{headers:sh}),d=await r.json();const u=d?.users||[];a.push(...u);if(u.length<200)break}return a};
const audit=async(a:string,t:any=null,d:any={})=>fetch(`${url}/rest/v1/admin_audit_log`,{method:'POST',headers:{...sh,Prefer:'return=minimal'},body:JSON.stringify({admin_user_id:me.id,action:a,target_user_id:t,details:d})});
const invite=async(email:string,first_name='',last_name='')=>{email=email.trim().toLowerCase();const r=await fetch(`${url}/auth/v1/admin/generate_link`,{method:'POST',headers:sh,body:JSON.stringify({type:'invite',email,data:{first_name,last_name,compassu_account_setup_required:true},redirect_to:`${app}/accept-invite`})});const d=await r.json();if(!r.ok)throw new Error(d?.msg||d?.message||'Unable to create invitation');const token=d?.properties?.hashed_token||d?.hashed_token;if(!token)throw new Error('Invitation token could not be generated.');const link=`${app}/accept-invite?token_hash=${encodeURIComponent(token)}&type=invite`;const html=`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto"><h1>CompassU</h1><h2>You’re invited to discover your direction.</h2><p>${esc(first_name)||'Hello'}, you’ve been invited to create your CompassU account and complete the career and college discovery assessment.</p><p style="margin:28px 0"><a href="${link}" style="background:#2f6fed;color:white;text-decoration:none;padding:15px 25px;border-radius:12px;font-weight:800">Create My CompassU Account →</a></p><p>If you were not expecting this invitation, you can ignore this email.</p></div>`;const rr=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${resend}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[email],subject:'You’re Invited to CompassU 🧭',html})});const rd=await rr.json();if(!rr.ok)throw new Error(rd?.message||'Unable to send invitation');return {user_id:d?.user?.id||d?.id||null,email,resend_id:rd?.id||null}};
if(action==='invite_user'){const users=await allUsers(),email=String(body.email||'').trim().toLowerCase();if(users.some((u:any)=>String(u.email||'').toLowerCase()===email))return json({error:'This email already has a CompassU account.'},409);const x=await invite(email,String(body.first_name||''),String(body.last_name||''));await audit('invite_user',x.user_id,{email,batch:false});return json({ok:true,message:'Invitation sent.'})}
if(action==='overview'||action==='refresh'){const users=await allUsers();const profiles=await fetch(`${url}/rest/v1/profiles?select=id,first_name,last_name,state,created_at`,{headers:sh}).then(r=>r.json());const attempts=await fetch(`${url}/rest/v1/assessment_attempts?select=id,user_id,status,started_at,completed_at`,{headers:sh}).then(r=>r.json());const pm=new Map((profiles||[]).map((p:any)=>[p.id,p]));const rows=users.map((u:any)=>{const p:any=pm.get(u.id)||{},aa=(attempts||[]).filter((x:any)=>x.user_id===u.id);return{id:u.id,email:u.email||'',first_name:p.first_name||u.user_metadata?.first_name||'',last_name:p.last_name||u.user_metadata?.last_name||'',state:p.state||'',created_at:u.created_at,last_sign_in_at:u.last_sign_in_at||null,email_confirmed_at:u.email_confirmed_at||null,assessment_count:aa.length,completed_surveys:aa.filter((x:any)=>x.status==='completed').length,in_progress_surveys:aa.filter((x:any)=>x.status==='in_progress').length,last_completed_at:aa.filter((x:any)=>x.completed_at).sort((a:any,b:any)=>b.completed_at.localeCompare(a.completed_at))[0]?.completed_at||null,is_suspended:Boolean(u.banned_until&&new Date(u.banned_until)>new Date()),banned_until:u.banned_until||null}});const completed=(attempts||[]).filter((x:any)=>x.status==='completed').length,cu=rows.filter((x:any)=>x.completed_surveys>0).length;return json({admin:{role:admins[0].role},stats:{total_accounts:users.length,completed_surveys:completed,accounts_with_completed_survey:cu,completion_rate:users.length?Math.round(cu/users.length*1000)/10:0,in_progress_surveys:(attempts||[]).filter((x:any)=>x.status==='in_progress').length,new_accounts_7d:0,new_accounts_30d:0,suspended_accounts:rows.filter((x:any)=>x.is_suspended).length},users:rows,trend:[]})}
if(action==='password_reset'){const id=String(body.user_id||''),u=(await allUsers()).find((x:any)=>x.id===id);if(!u?.email)return json({error:'Account email not found'},404);const r=await fetch(`${url}/auth/v1/recover`,{method:'POST',headers:{apikey:anon,'Content-Type':'application/json'},body:JSON.stringify({email:u.email})});if(!r.ok)return json({error:'Unable to send password reset'},r.status);await audit('password_reset',id,{email:u.email});return json({ok:true,message:'Password reset email sent.'})}
if(action==='suspend_user'||action==='reactivate_user'){const id=String(body.user_id||'');const r=await fetch(`${url}/auth/v1/admin/users/${id}`,{method:'PUT',headers:sh,body:JSON.stringify({ban_duration:action==='suspend_user'?'876000h':'none'})});if(!r.ok)return json({error:'Unable to update account status'},r.status);await audit(action,id,{});return json({ok:true,message:action==='suspend_user'?'Account suspended.':'Account reactivated.'})}
if(action==='delete_users'){const ids=[...new Set((Array.isArray(body.user_ids)?body.user_ids:[]).map((x:any)=>String(x||'')).filter(Boolean))];if(String(body.confirm||'')!=='DELETE')return json({error:'Type DELETE to confirm permanent account removal.'},400);if(!ids.length)return json({error:'Select at least one account.'},400);if(ids.length>100)return json({error:'Each bulk deletion request is limited to 100 accounts.'},400);const adminRows=await fetch(`${url}/rest/v1/admin_users?select=user_id&user_id=in.(${ids.join(',')})`,{headers:sh}).then(r=>r.json());const protectedIds=new Set((Array.isArray(adminRows)?adminRows:[]).map((x:any)=>String(x.user_id)));protectedIds.add(String(me.id));const users=await allUsers(),userMap=new Map(users.map((u:any)=>[String(u.id),u]));const results:any[]=[];for(const id of ids){const u:any=userMap.get(id);if(protectedIds.has(id)){results.push({user_id:id,email:u?.email||'',status:'Failed',message:'Administrator accounts cannot be removed through bulk deletion.'});continue}try{const r=await fetch(`${url}/auth/v1/admin/users/${id}`,{method:'DELETE',headers:sh});if(!r.ok){const d=await r.json().catch(()=>({}));results.push({user_id:id,email:u?.email||'',status:'Failed',message:d?.message||'Unable to remove account.'});continue}await audit('delete_user',id,{bulk:true});results.push({user_id:id,email:u?.email||'',status:'Deleted',message:'Account permanently removed.'})}catch(e){results.push({user_id:id,email:u?.email||'',status:'Failed',message:String((e as any)?.message||e)})}}return json({ok:true,results,summary:{requested:ids.length,deleted:results.filter((x:any)=>x.status==='Deleted').length,failed:results.filter((x:any)=>x.status==='Failed').length}})}
if(action==='delete_user'){const id=String(body.user_id||'');if(String(body.confirm||'')!=='DELETE')return json({error:'Type DELETE to confirm permanent account removal.'},400);const r=await fetch(`${url}/auth/v1/admin/users/${id}`,{method:'DELETE',headers:sh});if(!r.ok)return json({error:'Unable to remove account'},r.status);await audit('delete_user',id,{});return json({ok:true,message:'Account permanently removed.'})}
if(action==='audit_log'){const rows=await fetch(`${url}/rest/v1/admin_audit_log?select=id,action,target_user_id,details,created_at&order=created_at.desc&limit=100`,{headers:sh}).then(r=>r.json());return json({rows:Array.isArray(rows)?rows:[]})}
return json({error:'Unknown administrator action'},400)
}catch(e){return json({error:String((e as any)?.message||e)},500)}});
