-- Superseded by production migration 20260911231546_recovery_schema_baseline_for_tenant_admin_reporting_fixed.
-- The original recovery baseline exposed ordering problems during clean reconstruction because
-- RLS policies referenced helper functions that were not yet guaranteed to exist.
--
-- Do not use this file as the authoritative recovery baseline. See:
--   supabase/migrations/RECOVERY_PARITY_MANIFEST.md
-- and the production Supabase migration history beginning with version 20260911231546.
