import http from 'k6/http';
import { check, sleep } from 'k6';

const U=__ENV.SUPABASE_URL,K=__ENV.SUPABASE_KEY,P=__ENV.LOAD_TEST_PASSWORD;
if(!U||!K||!P)throw new Error('Missing load-test environment variables');
if(!U.includes('itmxtmasbslmciaopnow'))throw new Error('Refusing to run outside isolated load-test Supabase branch');
const FIX=50;
export const options={setupTimeout:'12m',scenarios:{
  student_day:{executor:'shared-iterations',vus:300,iterations:9000,maxDuration:'8m',exec:'student'},
  classroom_burst:{executor:'per-vu-iterations',vus:500,iterations:1,startTime:'2m',maxDuration:'3m',exec:'burst'},
  completion_wave:{executor:'per-vu-iterations',vus:100,iterations:1,startTime:'4m',maxDuration:'3m',exec:'finalize'},
  admin_activity:{executor:'shared-iterations',vus:20,iterations:400,startTime:'30s',maxDuration:'7m',exec:'admin'}
},thresholds:{'http_req_failed{phase:application}':['rate<0.01'],'http_req_duration{phase:application}':['p(95)<5000'],'http_req_duration{operation:finalize}':['p(95)<5000'],checks:['rate>0.99']}};
function h(t){return{apikey:K,Authorization:`Bearer ${t}`,'Content-Type':'application/json'};}
export function setup(){const f=[];for(let i=1;i<=FIX;i++){const n=String(i).padStart(3,'0');let t=null,u=null;for(let a=1;a<=8&&!t;a++){const r=http.post(`${U}/auth/v1/token?grant_type=password`,JSON.stringify({email:`compassu-loadtest-${n}@example.invalid`,password:P}),{headers:{apikey:K,'Content-Type':'application/json'},tags:{phase:'setup_auth'}});if(r.status===200){t=r.json('access_token');u=r.json('user.id')}else sleep(2)}if(!t)throw new Error(`auth ${n}`);f.push({t,u});sleep(.2)}const q=http.get(`${U}/rest/v1/assessment_questions?is_active=eq.true&select=id&order=question_number.asc`,{headers:h(f[0].t),tags:{phase:'setup'}}).json();if(!Array.isArray(q)||q.length!==80)throw new Error('Expected 80 questions');const finals=[];for(let i=0;i<100;i++){const x=f[i%FIX];const a=http.post(`${U}/rest/v1/assessment_attempts?select=id`,JSON.stringify({user_id:x.u}),{headers:{...h(x.t),Prefer:'return=representation'},tags:{phase:'setup'}});const id=a.json('0.id');if(!id)throw new Error(`attempt ${i}`);const rows=q.map((z,j)=>({attempt_id:id,user_id:x.u,question_id:z.id,response_value:{value:(j%5)+1}}));const r=http.post(`${U}/rest/v1/assessment_responses`,JSON.stringify(rows),{headers:h(x.t),tags:{phase:'setup'}});if(r.status<200||r.status>=300)throw new Error(`seed ${i}`);finals.push({id,t:x.t})}return{f,finals};}
function fixture(d){return d.f[(__VU-1)%FIX];}
export function student(d){const x=fixture(d);const p=http.get(`${U}/rest/v1/profiles?select=id&limit=1`,{headers:h(x.t),tags:{phase:'application',operation:'student_profile'}});check(p,{'student profile succeeds':r=>r.status===200});const q=http.get(`${U}/rest/v1/assessment_questions?is_active=eq.true&select=id,question_number&limit=20`,{headers:h(x.t),tags:{phase:'application',operation:'student_questions'}});check(q,{'student questions succeed':r=>r.status===200});sleep(.15);const m=http.get(`${U}/rest/v1/majors?active=eq.true&select=id,name&limit=10`,{headers:h(x.t),tags:{phase:'application',operation:'student_majors'}});check(m,{'student majors succeed':r=>r.status===200});}
export function burst(d){const x=fixture(d);const p=http.get(`${U}/rest/v1/profiles?select=id&limit=1`,{headers:h(x.t),tags:{phase:'application',operation:'burst_profile'}});check(p,{'burst profile succeeds':r=>r.status===200});const q=http.get(`${U}/rest/v1/assessment_questions?is_active=eq.true&select=id,question_number&limit=20`,{headers:h(x.t),tags:{phase:'application',operation:'burst_questions'}});check(q,{'burst questions succeed':r=>r.status===200});}
export function finalize(d){const x=d.finals[(__VU-1)%d.finals.length];const r=http.post(`${U}/rest/v1/rpc/finalize_assessment`,JSON.stringify({p_attempt_id:x.id}),{headers:h(x.t),tags:{phase:'application',operation:'finalize'}});check(r,{'completion succeeds':z=>z.status>=200&&z.status<300,'completion returns recommendations':z=>{try{return Array.isArray(z.json())&&z.json().length>0}catch{return false}}});}
export function admin(d){const x=fixture(d);const a=http.get(`${U}/rest/v1/assessment_attempts?select=id,status,completed_at&order=started_at.desc&limit=10`,{headers:h(x.t),tags:{phase:'application',operation:'admin_attempts'}});check(a,{'admin attempt query succeeds':r=>r.status===200});const mm=http.get(`${U}/rest/v1/major_matches?select=major_id,match_score,rank&limit=20`,{headers:h(x.t),tags:{phase:'application',operation:'admin_results'}});check(mm,{'admin result query succeeds':r=>r.status===200});sleep(.2);}
