import http from 'k6/http';
import { check, sleep } from 'k6';

const U=__ENV.SUPABASE_URL,K=__ENV.SUPABASE_KEY,P=__ENV.LOAD_TEST_PASSWORD;
if(!U||!K||!P)throw new Error('Missing load-test environment variables');
if(!U.includes('itmxtmasbslmciaopnow'))throw new Error('Refusing to run outside isolated load-test Supabase branch');
const FIX=50, ACTIVE=525, FINAL=150, READERS=75, TOTAL=750;
export const options={setupTimeout:'12m',scenarios:{mixed:{executor:'per-vu-iterations',vus:TOTAL,iterations:1,maxDuration:'5m'}},thresholds:{'http_req_failed{phase:application}':['rate<0.01'],'http_req_duration{phase:application}':['p(95)<5000'],'http_req_duration{operation:finalize}':['p(95)<5000'],checks:['rate>0.99']}};
function h(t){return{apikey:K,Authorization:`Bearer ${t}`,'Content-Type':'application/json'};}
export function setup(){const f=[];for(let i=1;i<=FIX;i++){const n=String(i).padStart(3,'0');let t=null,u=null;for(let a=1;a<=8&&!t;a++){const r=http.post(`${U}/auth/v1/token?grant_type=password`,JSON.stringify({email:`compassu-loadtest-${n}@example.invalid`,password:P}),{headers:{apikey:K,'Content-Type':'application/json'},tags:{phase:'setup_auth'}});if(r.status===200){t=r.json('access_token');u=r.json('user.id')}else sleep(2)}if(!t)throw new Error(`auth ${n}`);f.push({t,u});sleep(.2)}const q=http.get(`${U}/rest/v1/assessment_questions?is_active=eq.true&select=id&order=question_number.asc`,{headers:h(f[0].t),tags:{phase:'setup'}}).json();if(!Array.isArray(q)||q.length!==80)throw new Error('Expected 80 questions');const finals=[];for(let i=0;i<FINAL;i++){const x=f[i%FIX];const a=http.post(`${U}/rest/v1/assessment_attempts?select=id`,JSON.stringify({user_id:x.u}),{headers:{...h(x.t),Prefer:'return=representation'},tags:{phase:'setup'}});const id=a.json('0.id');if(!id)throw new Error(`attempt ${i}`);const rows=q.map((z,j)=>({attempt_id:id,user_id:x.u,question_id:z.id,response_value:{value:(j%5)+1}}));const r=http.post(`${U}/rest/v1/assessment_responses`,JSON.stringify(rows),{headers:h(x.t),tags:{phase:'setup'}});if(r.status<200||r.status>=300)throw new Error(`seed ${i}`);finals.push({id,t:x.t})}return{f,finals};}
export default function(d){const v=__VU;if(v<=ACTIVE){const x=d.f[(v-1)%FIX];const p=http.get(`${U}/rest/v1/profiles?select=id&limit=1`,{headers:h(x.t),tags:{phase:'application',operation:'profile'}});check(p,{'active profile read succeeds':r=>r.status===200});const q=http.get(`${U}/rest/v1/assessment_questions?is_active=eq.true&select=id,question_number&limit=20`,{headers:h(x.t),tags:{phase:'application',operation:'questions'}});check(q,{'active question read succeeds':r=>r.status===200});sleep(.25);const m=http.get(`${U}/rest/v1/majors?active=eq.true&select=id,name&limit=10`,{headers:h(x.t),tags:{phase:'application',operation:'majors'}});check(m,{'active major read succeeds':r=>r.status===200});}else if(v<=ACTIVE+FINAL){const x=d.finals[v-ACTIVE-1];const r=http.post(`${U}/rest/v1/rpc/finalize_assessment`,JSON.stringify({p_attempt_id:x.id}),{headers:h(x.t),tags:{phase:'application',operation:'finalize'}});check(r,{'mixed finalization succeeds':z=>z.status>=200&&z.status<300,'mixed finalization returns recommendations':z=>{try{return Array.isArray(z.json())&&z.json().length>0}catch{return false}}});}else{const x=d.f[(v-1)%FIX];const a=http.get(`${U}/rest/v1/assessment_attempts?select=id,status,completed_at&order=started_at.desc&limit=5`,{headers:h(x.t),tags:{phase:'application',operation:'history'}});check(a,{'history read succeeds':r=>r.status===200});const mm=http.get(`${U}/rest/v1/major_matches?select=major_id,match_score,rank&limit=10`,{headers:h(x.t),tags:{phase:'application',operation:'matches'}});check(mm,{'match read succeeds':r=>r.status===200});}}
